Repository nightven/agua_vivo_app_backend, pull requests merged in 2024-01, with the labels that each got.

#3 register router
  controllers/userControllers.js
  db/models/userModel.js
  db/services/userServices.js
  decorators/validateBody.js
  helpers/ctrlWrapper.js
  helpers/httpError.js
  routes/api/users.js
  schemas/usersShemas.js
Labels: enhancement

#2 added sentEmail method
  .env.example
  db/models/waterModel.js
  helpers/sendEmail.js
Labels: enhancement

#4 added HttError method and isValidId method
  helpers/httpError.js
  middlewares/isValidId.js
  routes/api/water.js
Labels: enhancement

#6 Auth/routes
  controllers/userControllers.js
  db/models/userModel.js
  db/services/userServices.js
  middlewares/authenticate.js
  routes/api/users.js
Labels: enhancement, help wanted

#7 added avatars
  controllers/userControllers.js
  db/services/userServices.js
  middlewares/upload.js
  public/avatars/65b26325c63af1dc9267269diimg.jpg
  routes/api/users.js
Labels: enhancement

#8 Auth/user info
  app.js
  controllers/userControllers.js
  db/models/userModel.js
  db/services/userServices.js
  middlewares/isValidId.js
  public/avatars/65b26325c63af1dc9267269diimg.jpg
  routes/api/users.js
  schemas/usersSchemas.js
Labels: enhancement, help wanted

#9 added rotes for water
  controllers/waterController.js
  db/models/waterModel.js
  db/services/waterServices.js
  helpers/amountDailyNorm.js
  helpers/httpError.js
  helpers/index.js
  routes/api/water.js
  schemas/waterSchemas.js
Labels: enhancement, wontfix

#10 daily norma of the water
  controllers/userControllers.js
  db/models/userModel.js
  helpers/amountNormaLitres.js
  helpers/index.js
  routes/api/users.js
  schemas/usersSchemas.js
Labels: enhancement, help wanted

#11 google start auth
  .env.example
  controllers/userControllers.js
  helpers/amountNormaLitres.js
  package-lock.json
  package.json
  routes/api/users.js
Labels: bug, enhancement, wontfix

#13 added auth endpoinds
  swagger.json
Labels: enhancement

#14 Water
  .env.example
  controllers/waterController.js
  db/models/waterModel.js
  db/services/waterServices.js
  helpers/amountDailyNorm.js
  helpers/amountMonthly.js
  helpers/httpError.js
  helpers/index.js
  routes/api/water.js
  schemas/waterSchemas.js
Labels: enhancement

#15 added beta version all routs
  .env.example
  app.js
  controllers/userControllers.js
  controllers/waterController.js
  db/models/userModel.js
  db/models/waterModel.js
  db/services/userServices.js
  db/services/waterServices.js
  decorators/validateBody.js
  helpers/amountDailyNorm.js
  helpers/amountMonthly.js
  helpers/amountNormaLitres.js
  helpers/ctrlWrapper.js
  helpers/handleMongooseError.js
  helpers/httpError.js
  helpers/index.js
  helpers/sendEmail.js
  middlewares/authenticate.js
  middlewares/isValidId.js
  middlewares/upload.js
  package-lock.json
  package.json
  routes/api/users.js
  routes/api/water.js
  schemas/usersSchemas.js
  schemas/usersShemas.js
  schemas/waterSchemas.js
  schemas/waterShemas.js
  swagger.json
Labels: enhancement

#16 deleted ruls for main
  .env.example
  controllers/userControllers.js
  package-lock.json
  package.json
Labels: fix

#17 fixed dailyNorma + upload cloudinary
  .env.example
  controllers/userControllers.js
  db/models/userModel.js
  db/services/userServices.js
  helpers/amountDailyNorm.js
  helpers/index.js
  middlewares/upload.js
  package-lock.json
  package.json
Labels: fix

#18 fixed rout water-rate, updated rout avatars to save avatar in cloudinary
  .env.example
  controllers/userControllers.js
  db/models/userModel.js
  db/services/userServices.js
  helpers/amountDailyNorm.js
  helpers/index.js
  middlewares/upload.js
  package-lock.json
  package.json
Labels: enhancement, fix

#19 patch replaced + google fixed
  .env.example
  controllers/userControllers.js
  db/models/userModel.js
  db/services/userServices.js
  routes/api/users.js
  schemas/usersSchemas.js
Labels: fix

#20 finished swagger v1.0.0
  controllers/waterController.js
  swagger.json
Labels: enhancement

#21 Water
  controllers/waterController.js
  db/models/waterModel.js
  db/services/waterServices.js
  helpers/amountMonthly.js
  routes/api/water.js
  schemas/waterSchemas.js
Labels: enhancement, fix

#22 Water
  controllers/waterController.js
  routes/api/water.js
Labels: fix

#23 Auth/fix
  app.js
  controllers/authController.js
  controllers/googleController.js
  controllers/userControllers.js
  db/models/userModel.js
  db/services/authService.js
  db/services/googleServices.js
  db/services/userServices.js
  helpers/sendEmail.js
  middlewares/index.js
  middlewares/isEmptyBody.js
  package-lock.json
  package.json
  routes/api/auth.js
  routes/api/google.js
  routes/api/users.js
  schemas/authSchema.js
  schemas/usersSchemas.js
Labels: enhancement, fix

#24 water changes
  controllers/waterController.js
  db/services/waterServices.js
  routes/api/water.js
  schemas/waterSchemas.js
Labels: fix

#25 Swagger
  swagger.json
Labels: fix

#26 update 2.0
  .env.example
  app.js
  controllers/authController.js
  controllers/googleController.js
  controllers/userControllers.js
  controllers/waterController.js
  db/models/userModel.js
  db/models/waterModel.js
  db/services/authService.js
  db/services/googleServices.js
  db/services/userServices.js
  db/services/waterServices.js
  helpers/amountMonthly.js
  helpers/sendEmail.js
  middlewares/index.js
  middlewares/isEmptyBody.js
  package-lock.json
  package.json
  routes/api/auth.js
  routes/api/google.js
  routes/api/users.js
  routes/api/water.js
  schemas/authSchema.js
  schemas/usersSchemas.js
  schemas/waterSchemas.js
  swagger.json
Labels: enhancement, fix

#27 water fixes
  controllers/waterController.js
  db/services/waterServices.js
  middlewares/index.js
  middlewares/isValidId.js
  middlewares/isValidMonth.js
  routes/api/water.js
  schemas/waterSchemas.js
Labels: enhancement, fix

#29 backend added
  controllers/authController.js
Labels: fix

#28 Update water rout and swagger
  controllers/authController.js
  controllers/waterController.js
  db/services/waterServices.js
  middlewares/index.js
  middlewares/isValidId.js
  middlewares/isValidMonth.js
  routes/api/water.js
  schemas/waterSchemas.js
  swagger.json
Labels: enhancement, fix

#30 Auth/google
  .env.example
  controllers/googleController.js
  db/models/userModel.js
  db/services/googleServices.js
  package-lock.json
  package.json
  schemas/usersSchemas.js
Labels: enhancement
