Repository nightven/agua_vivo_app_backend, pull requests merged in 2024-02, with the labels that each got.

#31 gender fix
  db/models/userModel.js
  schemas/usersSchemas.js
Labels: fix

#32 updated swagger
  swagger.json
Labels: fix

#33 update user rout and swagger
  .env.example
  controllers/googleController.js
  db/models/userModel.js
  db/services/googleServices.js
  package-lock.json
  package.json
  schemas/usersSchemas.js
  swagger.json
Labels: enhancement, fix

#34 delete + update
  db/services/waterServices.js
  middlewares/isValidId.js
Labels: enhancement, fix

#35 Delete + update
  db/services/waterServices.js
  middlewares/isValidId.js
Labels: fix

#36 Update swagger.json
  swagger.json
Labels: fix

#37 added response id in delete controllers
  controllers/waterController.js
Labels: fix

#38 update response from delete rout
  controllers/waterController.js
Labels: fix

#39 apdated swager and water response in contrlollers
  controllers/waterController.js
  swagger.json
Labels: fix

#40 some fixes
  controllers/authController.js
  db/services/waterServices.js
Labels: fix

#42 updated getWaterVolume
  db/services/waterServices.js
Labels: fix

#43 DailyNorm
  controllers/authController.js
  controllers/userControllers.js
  controllers/waterController.js
  db/services/waterServices.js
Labels: enhancement, fix

#44 update password
  controllers/userControllers.js
  schemas/usersSchemas.js
Labels: enhancement

#45 Auth/email required
  .env.example
  controllers/authController.js
  db/services/authService.js
  helpers/sendEmail.js
  package-lock.json
  package.json
Labels: help wanted, fix

#46 forgot + reset password
  controllers/authController.js
  controllers/userControllers.js
  db/services/authService.js
  routes/api/auth.js
  schemas/authSchema.js
Labels: enhancement, fix

#47 updated logic for forgot and reset pasword
  controllers/authController.js
  routes/api/auth.js
  schemas/authSchema.js
Labels: fix

#48 for render
  controllers/authController.js
  controllers/googleController.js
Labels: fix

#49 Forgot, reset password, google auth, verifiy email, update password
  .env.example
  controllers/authController.js
  controllers/googleController.js
  controllers/userControllers.js
  controllers/waterController.js
  db/services/authService.js
  db/services/waterServices.js
  helpers/sendEmail.js
  package-lock.json
  package.json
  routes/api/auth.js
  schemas/authSchema.js
  schemas/usersSchemas.js
Labels: enhancement

#50 google fix
  controllers/googleController.js
Labels: fix

#51 google fix
  controllers/googleController.js
Labels: enhancement, fix

#52 again front fix
  controllers/authController.js
Labels: fix

#53 again front fix
  controllers/authController.js
Labels: fix

#54 added created water for google Auth
  controllers/authController.js
  controllers/googleController.js
  db/services/waterServices.js
Labels: fix

#55 added create wayter for google auth
  controllers/authController.js
  controllers/googleController.js
  db/services/waterServices.js
Labels: fix

#56 messages + token
  controllers/authController.js
  controllers/googleController.js
  email/messages.js
  public/avatars/.gitkeep
  temp/.gitkeep
Labels: documentation, enhancement, fix

#57 messages + token
  controllers/authController.js
  controllers/googleController.js
  email/messages.js
  public/avatars/.gitkeep
  temp/.gitkeep
Labels: fix

#58 updated actual swager
  controllers/waterController.js
  swagger.json
Labels: fix

#59 Update swagger
  controllers/waterController.js
  swagger.json
Labels: documentation, enhancement, fix

#60 regexSchemas + token
  controllers/authController.js
  controllers/googleController.js
  db/models/waterModel.js
  db/public/regex.js
  middlewares/isValidMonth.js
  schemas/authSchema.js
  schemas/waterSchemas.js
Labels: fix

#61 update swagger, delete console.log
  db/services/waterServices.js
  swagger.json
Labels: fix

#62 fix delete
  controllers/authController.js
  controllers/googleController.js
  db/models/waterModel.js
  db/public/regex.js
  db/services/waterServices.js
  middlewares/isValidMonth.js
  schemas/authSchema.js
  schemas/waterSchemas.js
  swagger.json
Labels: fix

#63 fix get month rout in swagger
  swagger.json
Labels: enhancement

#64 fix swagger
  swagger.json
Labels: fix

#65 fix response code
  swagger.json
Labels: fix

#66 fix response code
  swagger.json
Labels: fix

#67 styled for email
  email/messages.js
Labels: enhancement

#68 reset message
  email/messages.js
Labels: enhancement, fix

#69 styles for email
  email/messages.js
Labels: enhancement

#71 Sofiialives patch 1
  README.en.md
  README.md
Labels: enhancement, fix

#73 Sofiialives patch 1
  README.en.md
  README.md
Labels: fix

#74 Update README.md
  README.en.md
  README.md
Labels: fix

#76 refactored controllers and services for water
  controllers/waterController.js
  db/services/waterServices.js
Labels: fix

#77 refactoring water services
  controllers/waterController.js
  db/services/waterServices.js
Labels: fix

#80 fixed get today response
  controllers/waterController.js
Labels: fix

#79 fixed register controller
  controllers/authController.js
  controllers/waterController.js
Labels: fix
